//! Sparse accumulator for Hough-transform seeding.
//!
//! This module implements the low-level vote accumulation stage used by the
//! Hough seeding pipeline. For each angular-velocity hypothesis, alerts are
//! back-projected to a common reference epoch and quantized into a sparse grid
//! over projected sky position. Each occupied grid cell stores both the total
//! vote weight and the set of contributing alert indices.
//!
//! The accumulator is sparse by construction: only bins that receive at least
//! one vote are stored. This keeps the search tractable even when the velocity
//! grid is dense and the alert set is large.
//!
//! ## Scientific role
//!
//! For one velocity hypothesis $(v\_\alpha, v\_\delta)$ and one alert with
//! sky position $(\alpha, \delta)$ observed at time $t$, the projection used by
//! the Hough search is
//!
//! $$\begin{align} \alpha\_0 &= \mathrm{wrap}\_{\pi}(\alpha - v\_\alpha \Delta t) \\\ \delta\_0 &= \delta - v\_\delta \Delta t \end{align}$$
//!
//! where $\Delta t$ is measured relative to the reference epoch of the night.
//! The projected coordinates are discretized using `spatial_bin_size`, and the
//! resulting cell identifies one local Hough maximum candidate.
//!
//! ## Main items
//!
//! - [`AccumulatorCell`] stores the vote weight and alert membership of one
//!   sparse cell.
//! - [`AccKey`] identifies one velocity-position bin in the accumulator.
//! - [`AccKey::hough_bins_are_close`] compares two cells using the NMS bin
//!   neighborhood.
//! - [`build_hough_accumulator`] fills the sparse accumulator from a night of
//!   alerts.

use ahash::AHashMap;

use crate::{
    Alert,
    astro_math::wrap_pm_pi,
    engine_config::seeding_config::HoughSeedingConfig,
    seeding::hough::{nms::NMS_MAX_BIN_OFFSET, vote_weight},
};

/// Sparse accumulator cell attached to one velocity hypothesis and one spatial bin.
///
/// A cell aggregates all alerts that project to the same discretized sky bin
/// under the same velocity hypothesis. The `score` is the sum of vote weights,
/// while `alert_indices` records the member alerts that support the cell.
#[derive(Clone, Debug, Default)]
pub struct AccumulatorCell {
    /// Sum of vote weights contributed by the alerts mapped to this cell.
    pub score: f64,
    /// Indices of the alerts that voted for this cell.
    pub alert_indices: Vec<usize>,
}

/// Key used to index the sparse Hough accumulator.
///
/// The key combines a discrete velocity-grid location with the quantized
/// projected sky position. Two keys are considered spatially close when their
/// indices differ by at most the NMS neighborhood threshold on every axis.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct AccKey {
    /// X index in the velocity grid.
    pub vel_ix: usize,
    /// Y index in the velocity grid.
    pub vel_iy: usize,
    /// Discretized projected right ascension bin.
    pub alpha_bin: i32,
    /// Discretized projected declination bin.
    pub delta_bin: i32,
}

impl AccKey {
    /// Return true if two Hough bins are spatially and kinematically adjacent.
    ///
    /// This comparison is used by the Hough NMS stage to identify peaks that
    /// arise from nearly identical velocity hypotheses and projected sky bins.
    /// The threshold is controlled by
    /// [`NMS_MAX_BIN_OFFSET`].
    ///
    /// Arguments
    /// ---------
    /// * `b` - Second accumulator key to compare with `self`.
    ///
    /// Return
    /// ------
    /// * `true` - The two keys are within the configured neighborhood in all
    ///   four dimensions.
    /// * `false` - At least one axis differs by more than the allowed offset.
    #[inline]
    pub fn hough_bins_are_close(&self, b: &AccKey) -> bool {
        ((self.vel_ix as i64 - b.vel_ix as i64).abs() as i32) <= NMS_MAX_BIN_OFFSET
            && ((self.vel_iy as i64 - b.vel_iy as i64).abs() as i32) <= NMS_MAX_BIN_OFFSET
            && (self.alpha_bin - b.alpha_bin).abs() <= NMS_MAX_BIN_OFFSET
            && (self.delta_bin - b.delta_bin).abs() <= NMS_MAX_BIN_OFFSET
    }
}

/// Accumulate sparse Hough votes over all velocity hypotheses.
///
/// For each velocity hypothesis and each alert, the alert is projected back to
/// the reference epoch, quantized into a spatial bin, and used to update the
/// corresponding sparse accumulator cell. The function stores only occupied
/// cells, together with the indices of the alerts that contributed to them.
///
/// Arguments
/// ---------
/// * `alerts` - Alerts belonging to one night.
/// * `cfg` - Hough configuration controlling the spatial bin size and vote
///   weighting.
/// * `vel_grid` - Velocity hypotheses generated by the Hough search.
/// * `t_ref` - Reference epoch used to define $\Delta t$.
///
/// Return
/// ------
/// * `AHashMap<AccKey, AccumulatorCell>` - Sparse accumulator keyed by the
///   combined velocity and projected sky bin.
pub fn build_hough_accumulator(
    alerts: &[Alert],
    cfg: &HoughSeedingConfig,
    vel_grid: &[(usize, usize, f64, f64)],
    t_ref: f64,
) -> AHashMap<AccKey, AccumulatorCell> {
    let mut acc: AHashMap<AccKey, AccumulatorCell> = AHashMap::new();

    for &(ix, iy, vx, vy) in vel_grid {
        for (alert_idx, alert) in alerts.iter().enumerate() {
            // Project the alert back to the reference epoch under one velocity model.
            let dt = alert.mjd_tt - t_ref;
            if !dt.is_finite() {
                continue;
            }
            let alpha0 = wrap_pm_pi(alert.ra - vx * dt);
            let delta0 = alert.dec - vy * dt;
            if !alpha0.is_finite() || !delta0.is_finite() {
                continue;
            }
            if delta0.abs() > std::f64::consts::FRAC_PI_2 + 1e-6 {
                continue;
            }

            let alpha_bin = (alpha0 / cfg.spatial_bin_size).floor() as i32;
            let delta_bin = (delta0 / cfg.spatial_bin_size).floor() as i32;
            let key = AccKey {
                vel_ix: ix,
                vel_iy: iy,
                alpha_bin,
                delta_bin,
            };
            let cell = acc.entry(key).or_default();
            cell.score += vote_weight(alert, cfg);
            cell.alert_indices.push(alert_idx);
        }
    }

    acc
}
