[package]
name = "fink-fat"
version = "1.0.0"
edition = "2024"

[workspace]
members = [
    "crates/fink-fat-engine",
]
resolver = "2"

[dependencies]
ahash = "0.8.12"
camino = "1.2.1"
cdshealpix = "0.7.3"
indicatif = "0.18.0"
itertools = "0.14.0"
numpy = "0.26.0"
pyo3 = { version = "0.26", features = ["extension-module"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
toml = "0.9.8"

[dev-dependencies]
criterion = "0.7.0"
husky-rs = "0.1.5"
proptest = "1.8.0"
rand = "0.9.2"
tempfile = "3.23.0"


[profile.release]
debug = true      # conserve les symboles
strip = "none"
lto = "thin"
codegen-units = 1
