[workspace.package]
edition = "2024"
version = "1.0.0"
authors = ["Roman Le Montagner <roman.le-montagner@ijclab.in2p3.fr>"]
categories = ["science"]
license-file = "LICENSE"

[package]
name = "fink-fat"
readme = "README.md"
description = "FINK-FAT: Fink Asteroid Tracker, a software to track asteroids in an alert stream such as Fink's.It provides a graph-based representation of the linked alerts and implements algorithms to predict potential asteroid detections and track them over time."
edition.workspace = true
version.workspace = true
authors.workspace = true
categories.workspace = true
license-file.workspace = true

[workspace]
members = ["crates/fink-fat-engine"]
resolver = "2"

[workspace.dependencies]
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
camino = "1.2.1"
tempfile = "3.23.0"

[dependencies]
clap = "4.5.60"
indicatif = "0.18.0"

[dev-dependencies]
husky-rs = "0.1.5"

[profile.release]
opt-level = 3
strip = "none"
lto = "thin"
codegen-units = 1

[profile.bench]
opt-level = 3
lto = "thin"
codegen-units = 1
debug = true
