[package]
name = "fink-fat-engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
license-file.workspace = true
readme = "README.md"
description = "Core engine for the Fink-FAT asteroid detection pipeline."

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
camino = { workspace = true }
tracing = { workspace = true }
ahash = { workspace = true }
photom = { workspace = true, features = ["serde"] }
outfit = { workspace = true, features = ["serde"]}
rkyv = { workspace = true, features = ["pointer_width_64"] }
memmap2 = { workspace = true }

nalgebra = { version = "0.34.2" }
hifitime = { version = "4.2.0", default-features = false, features = [
    "ut1",
    "std",
] }

cdshealpix = "0.7.3"
config = "0.15.19"
serde_json = "1.0.145"
rayon = "1.12.0"

[dev-dependencies]
approx = "0.5.1"
# criterion = "0.8.1"
proptest = "1.9.0"
serde_yaml = { workspace = true }
tracing-subscriber = { workspace = true }
# tempfile = { workspace = true }
# photom = { workspace = true, features = ["serde", "datafusion"] }
