//! Intra-night observation pairing → Kalman-filter bank seeding.
//!
//! This module turns a [`photom::observation_dataset::ObsDataset`] into a
//! collection of [`topocentric_kf::kalman_bank::KFBank`] hypotheses banks:
//!
//! 1. Observations are scoped to a single night (seeds never mix nights).
//! 2. Candidate observation pairs within that night are generated by
//!    [`pairs::generate_pairs`] (time/angular-speed/magnitude gating).
//! 3. Each surviving pair seeds one [`topocentric_kf::kalman_bank::KFBank`]
//!    via `KFBank::from_grid`.
//!
//! See [`kf_bank_builder::build_kf_bank_collection`] for the top-level entry
//! point.

pub mod error;
pub mod pairs;
pub mod triplets;
