//! Submitter/telescope identity, shared by every producer and consumer of
//! it: `fink-fat submit`'s `--submitter-config` YAML file
//! (`fink-fat`'s `SubmitterConfig::load`/`load_submitter_config`),
//! `fink-fat-explorer`'s generator form on the Submission page (which
//! downloads exactly this type serialized as YAML — see [`SubmitterConfig::to_yaml`]),
//! and its lineage-page ADES export modal (which converts straight to
//! [`crate::model::AdesHeaderInput`] via [`SubmitterConfig::into_header`]
//! without ever touching YAML). One type, one validation rule set, used
//! everywhere this data crosses a boundary — a value generated by the
//! explorer's form is guaranteed to load back through `fink-fat submit`
//! without surprises.

use serde::{Deserialize, Serialize};

use crate::model::AdesHeaderInput;

/// Submitter/telescope identity fields not tracked by the fink-fat
/// pipeline. Mirrors [`AdesHeaderInput`] field for field, except
/// `ack_message` stays optional here: when left unset (or blank), one is
/// generated per lineage by [`default_ack_message`] rather than a single
/// fixed string being reused, verbatim, across every lineage in a batch.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct SubmitterConfig {
    pub submitter_name: String,
    pub submitter_institution: Option<String>,
    pub observers: Vec<String>,
    pub measurers: Vec<String>,
    pub telescope_design: String,
    pub telescope_aperture: String,
    pub telescope_detector: String,
    pub ast_cat: String,
    pub mode: String,
    pub funding_source: Option<String>,
    pub ack_message: Option<String>,
    pub ac2_email: String,
}

impl SubmitterConfig {
    /// Which required fields are missing or blank. Pure — the actual
    /// per-observation `submit.xsd` checks still run later, per lineage, via
    /// [`crate::schema_validation::check_local_schema_violations`]; this
    /// only catches header-level mistakes worth failing fast on (or
    /// flagging inline in a form) before that.
    ///
    /// # Return
    /// A human-readable reason per missing field; empty means valid.
    pub fn validation_errors(&self) -> Vec<String> {
        let mut reasons = Vec::new();
        if self.submitter_name.trim().is_empty() {
            reasons.push("submitter_name is required".to_string());
        }
        if self.measurers.iter().all(|m| m.trim().is_empty()) {
            reasons.push("at least one measurer is required".to_string());
        }
        if self.telescope_design.trim().is_empty() {
            reasons.push("telescope_design is required".to_string());
        }
        if self.telescope_aperture.trim().is_empty() {
            reasons.push("telescope_aperture is required".to_string());
        }
        if self.telescope_detector.trim().is_empty() {
            reasons.push("telescope_detector is required".to_string());
        }
        if self.ast_cat.trim().is_empty() {
            reasons.push("ast_cat is required".to_string());
        }
        if self.mode.trim().is_empty() {
            reasons.push("mode is required".to_string());
        }
        if self.ac2_email.trim().is_empty() {
            reasons.push("ac2_email is required".to_string());
        }
        reasons
    }

    /// Builds one lineage's ADES header. Pure given `today` (the caller
    /// supplies it, e.g. via [`crate::format_epoch::today_utc_date`], rather
    /// than this function reading the clock itself, so it stays testable
    /// without mocking time). A blank or unset `ack_message` is replaced by
    /// [`default_ack_message`].
    ///
    /// # Arguments
    /// * `lineage_designation` — the lineage this header is for.
    /// * `today` — today's UTC date (`YYYY-MM-DD`), used only when
    ///   `ack_message` wasn't configured.
    ///
    /// # Return
    /// The [`AdesHeaderInput`].
    pub fn into_header(self, lineage_designation: &str, today: &str) -> AdesHeaderInput {
        let ack_message = self
            .ack_message
            .filter(|s| !s.trim().is_empty())
            .unwrap_or_else(|| default_ack_message(lineage_designation, today));
        AdesHeaderInput {
            submitter_name: self.submitter_name,
            submitter_institution: self.submitter_institution,
            observers: self.observers,
            measurers: self.measurers,
            telescope_design: self.telescope_design,
            telescope_aperture: self.telescope_aperture,
            telescope_detector: self.telescope_detector,
            ast_cat: self.ast_cat,
            mode: self.mode,
            funding_source: self.funding_source,
            ack_message,
            ac2_email: self.ac2_email,
        }
    }

    /// Serializes this config to YAML — the exact shape `fink-fat submit
    /// --submitter-config` reads back (round-trip tested below).
    ///
    /// # Return
    /// The YAML text.
    ///
    /// # Errors
    /// Returns `serde_yaml::Error` if serialization itself fails (not
    /// expected for this plain-data shape, but not `unwrap`-safe per repo
    /// convention).
    pub fn to_yaml(&self) -> Result<String, serde_yaml::Error> {
        serde_yaml::to_string(self)
    }
}

/// The default per-lineage acknowledgement message, used when a
/// [`SubmitterConfig`] doesn't set one — carries the lineage designation and
/// submission date so MPC's eventual report can be matched back without the
/// user typing anything.
///
/// # Arguments
/// * `lineage_designation` — the lineage being submitted.
/// * `today` — today's UTC date (`YYYY-MM-DD`).
///
/// # Return
/// The ack message text.
pub fn default_ack_message(lineage_designation: &str, today: &str) -> String {
    format!("fink-fat submit - lineage {lineage_designation} - {today}")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_config() -> SubmitterConfig {
        SubmitterConfig {
            submitter_name: "Jane Doe".to_string(),
            submitter_institution: None,
            observers: vec![],
            measurers: vec!["Jane Doe".to_string()],
            telescope_design: "Reflector".to_string(),
            telescope_aperture: "1.2".to_string(),
            telescope_detector: "CCD".to_string(),
            ast_cat: "Gaia2".to_string(),
            mode: "CCD".to_string(),
            funding_source: None,
            ack_message: None,
            ac2_email: "user@example.com".to_string(),
        }
    }

    #[test]
    fn validation_errors_empty_for_a_complete_config() {
        assert!(valid_config().validation_errors().is_empty());
    }

    #[test]
    fn validation_errors_reports_every_missing_field() {
        let reasons = SubmitterConfig::default().validation_errors();
        assert_eq!(reasons.len(), 8, "{reasons:?}");
    }

    #[test]
    fn into_header_generates_ack_message_when_absent() {
        let header = valid_config().into_header("FF2026abc", "2026-09-24");
        assert!(header.ack_message.contains("FF2026abc"));
    }

    #[test]
    fn into_header_generates_ack_message_when_blank() {
        let mut config = valid_config();
        config.ack_message = Some("   ".to_string());
        let header = config.into_header("FF2026abc", "2026-09-24");
        assert!(header.ack_message.contains("FF2026abc"));
    }

    #[test]
    fn into_header_keeps_a_configured_ack_message_verbatim() {
        let mut config = valid_config();
        config.ack_message = Some("custom ack".to_string());
        let header = config.into_header("FF2026abc", "2026-09-24");
        assert_eq!(header.ack_message, "custom ack");
    }

    #[test]
    fn to_yaml_round_trips_through_deserialization() {
        let config = valid_config();
        let yaml = config.to_yaml().unwrap();
        let parsed: SubmitterConfig = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed, config);
    }

    #[test]
    fn default_ack_message_carries_lineage_and_date() {
        let msg = default_ack_message("FF2026abc", "2026-09-24");
        assert!(msg.contains("FF2026abc"));
        assert!(msg.contains("2026-09-24"));
    }
}
