[package]
name = "fink-fat-eval"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
camino = "1.2.2"
polars = { version = "=0.52.0", default-features = false, features = [
    "lazy",
    "parquet",
    "fmt",
    "is_in"
] }
fink-fat-engine = { path = "../fink-fat-engine" }
comfy-table = "7.2.1"
plotters = "0.3.7"
clap = { version = "4.5.53", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
prop-test = "0.1.1"

[[bin]]
name = "pairs_posthoc_sweep"
path = "src/bin/seeding/pairs_posthoc_sweep.rs"

[[bin]]
name = "pairs-multinight"
path = "src/bin/seeding/pairs_multinight.rs"

[[bin]]
name = "score-distribution"
path = "src/bin/scoring/score_distribution.rs"
