#!/bin/sh

echo "Running cargo fmt..."
cargo fmt --all -- --check || exit 1

echo "Running cargo clippy..."
cargo clippy --all-targets --all-features -- -D warnings || exit 1

echo "Running cargo check..."
cargo check --all-targets --all-features || exit 1

echo "Checking documentation build..."
RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all-features || exit 1
