#!/bin/sh

echo "Running cargo fmt..."
cargo fmt --all -- --check || exit 1

echo "Running cargo clippy..."
cargo clippy --all-targets --all-features -- -D warnings || exit 1

echo "Running cargo check..."
cargo check --all-targets --all-features || exit 1

echo "Checking documentation build..."
RUSTDOCFLAGS="-D warnings --html-in-header $(pwd)/katex-header.html" cargo doc --no-deps --all-features -p fink-fat -p fink-fat-engine || exit 1
